env:
  browser: true
  es6: true
extends:
   - "walmart/rules/eslint/best-practices/on"
   - "walmart/rules/eslint/es6/off"
   - "walmart/rules/eslint/node/on"
 
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 4
